---
title: "Introduction"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Background Information

We all love watching movies, and our emotions and perspectives are ,oftentimes, affected by the plot. We might cry when the little boy in the film died in a car accident, or feel anger when the villians win. Under this observation and assumption, we believe there is a possibility that movies shown in theatres contribute to social atmosphere, which in turn may influence crime rate. Movies that may trigger aggression, such as those belonging to the "crime", "thriller", and "horror" genre, may lead to real-world violence. On the other hand, movies that receive wide acclaim may bring more satisfaction and delight to the audience, which may lead to less negative behavior, and therefore a lower crime rate. 

## Problem Definition

Our aim is to investigate the effects of different movie factors on total crime cases each quarter, from 2008-2015.

In the first model, we will examine **the effect of movie type**. In the second model, we will examine **the effect of log box office results** and **the effect of movie scores**.

## Data Source

1. Movie/ Box Office Results

+ Taipei's Top 15 Movies From 2008-2015 (by quarter):

+ <http://www.tfi.org.tw/word/Yearbook/2008_Taiwan_Cinema_Yearbook.pdf>

+ <http://www.tfi.org.tw/word/Yearbook/2009_Taiwan_Cinema_Yearbook.pdf>

+ <http://www.tfi.org.tw/word/Yearbook/2010_Taiwan_Cinema_Yearbook.pdf>

+ <http://www.tfi.org.tw/word/Yearbook/2011_Taiwan_Cinema_Yearbook.pdf>

+ <http://www.tfi.org.tw/word/Yearbook/2012_Taiwan_Cinema_Yearbook.pdf>

+ <http://www.tfi.org.tw/word/Yearbook/2013_Taiwan_Cinema_Yearbook.pdf>

+ <http://www.tfi.org.tw/word/Yearbook/2014_Taiwan_Cinema_Yearbook.pdf>

+ <http://www.tfi.org.tw/word/Yearbook/2015_Taiwan_Cinema_Yearbook.pdf>


2. Crime cases

+ Department of Statistics in Ministry of the Interior: <https://www.moi.gov.tw/stat/chart.aspx?ChartID=S0301>


3. Movie Scores 

+ IMDb: <http://www.imdb.com/>

+ Rotten Tomatoes: <https://www.rottentomatoes.com/>
